version: '3.8'

services:
  docker-pulse:
    build: .
    container_name: docker-pulse
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Wichtig, damit das Tool die Docker-Container auf dem Host überwachen kann!
    environment:
      - DISCORD_WEBHOOK_URL=dein_webhook_hier_einfügen